package org.cyk.system.root.persistence.impl.mathematics.movement;

import java.io.Serializable;

import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifier;
import org.cyk.system.root.persistence.api.mathematics.movement.MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifierDao;
import org.cyk.system.root.persistence.impl.globalidentification.AbstractJoinGlobalIdentifierDaoImpl;

public class MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifierDaoImpl extends AbstractJoinGlobalIdentifierDaoImpl<MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifier,MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifier.SearchCriteria> implements MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifierDao,Serializable {
	private static final long serialVersionUID = 6306356272165070761L;
	

}
 