package org.cyk.system.root.persistence.impl.mathematics.movement;

import java.io.Serializable;

import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollection;
import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollectionItem;
import org.cyk.system.root.persistence.api.mathematics.movement.MovementCollectionValuesTransferItemCollectionDao;

public class MovementCollectionValuesTransferItemCollectionDaoImpl extends AbstractMovementCollectionsDaoImpl<MovementCollectionValuesTransferItemCollection,MovementCollectionValuesTransferItemCollectionItem> implements MovementCollectionValuesTransferItemCollectionDao,Serializable {

	private static final long serialVersionUID = 6152315795314899083L;

}
