package org.cyk.system.root.business.impl.mathematics.movement;

import java.io.Serializable;

import javax.inject.Inject;

import org.cyk.system.root.business.api.mathematics.movement.MovementsTransferItemCollectionItemIdentifiableGlobalIdentifierBusiness;
import org.cyk.system.root.business.impl.globalidentification.AbstractJoinGlobalIdentifierBusinessImpl;
import org.cyk.system.root.model.mathematics.movement.MovementsTransferItemCollectionItemIdentifiableGlobalIdentifier;
import org.cyk.system.root.persistence.api.mathematics.movement.MovementsTransferItemCollectionItemIdentifiableGlobalIdentifierDao;

public class MovementsTransferItemCollectionItemIdentifiableGlobalIdentifierBusinessImpl extends AbstractJoinGlobalIdentifierBusinessImpl<MovementsTransferItemCollectionItemIdentifiableGlobalIdentifier, MovementsTransferItemCollectionItemIdentifiableGlobalIdentifierDao,MovementsTransferItemCollectionItemIdentifiableGlobalIdentifier.SearchCriteria> implements MovementsTransferItemCollectionItemIdentifiableGlobalIdentifierBusiness,Serializable {

	private static final long serialVersionUID = -3799482462496328200L;

	@Inject
	public MovementsTransferItemCollectionItemIdentifiableGlobalIdentifierBusinessImpl(MovementsTransferItemCollectionItemIdentifiableGlobalIdentifierDao dao) {
		super(dao); 
	}
	
}
