package org.cyk.system.root.persistence.api.information;

import org.cyk.system.root.model.information.IdentifiableCollectionItemIdentifiableGlobalIdentifier;
import org.cyk.system.root.persistence.api.globalidentification.JoinGlobalIdentifierDao;

public interface IdentifiableCollectionItemIdentifiableGlobalIdentifierDao extends JoinGlobalIdentifierDao<IdentifiableCollectionItemIdentifiableGlobalIdentifier,IdentifiableCollectionItemIdentifiableGlobalIdentifier.SearchCriteria> {
	
}
