package org.cyk.system.root.business.api.information;

import org.cyk.system.root.business.api.globalidentification.JoinGlobalIdentifierBusiness;
import org.cyk.system.root.model.information.IdentifiableCollectionItemIdentifiableGlobalIdentifier;

public interface IdentifiableCollectionItemIdentifiableGlobalIdentifierBusiness extends JoinGlobalIdentifierBusiness<IdentifiableCollectionItemIdentifiableGlobalIdentifier,IdentifiableCollectionItemIdentifiableGlobalIdentifier.SearchCriteria> {
	
}
