package org.cyk.system.root.business.api.information;

import org.cyk.system.root.business.api.globalidentification.JoinGlobalIdentifierBusiness;
import org.cyk.system.root.model.information.InformationStateIdentifiableGlobalIdentifier;

public interface InformationStateIdentifiableGlobalIdentifierBusiness extends JoinGlobalIdentifierBusiness<InformationStateIdentifiableGlobalIdentifier,InformationStateIdentifiableGlobalIdentifier.SearchCriteria> {
	
}
