package org.cyk.system.root.persistence.api.time;

import org.cyk.system.root.model.time.IdentifiablePeriodCollectionIdentifiableGlobalIdentifier;
import org.cyk.system.root.persistence.api.globalidentification.JoinGlobalIdentifierDao;

public interface IdentifiablePeriodCollectionIdentifiableGlobalIdentifierDao extends JoinGlobalIdentifierDao<IdentifiablePeriodCollectionIdentifiableGlobalIdentifier,IdentifiablePeriodCollectionIdentifiableGlobalIdentifier.SearchCriteria> {
	
}
