package org.cyk.system.root.business.api.time;

import org.cyk.system.root.business.api.globalidentification.JoinGlobalIdentifierBusiness;
import org.cyk.system.root.model.time.IdentifiablePeriodIdentifiableGlobalIdentifier;

public interface IdentifiablePeriodIdentifiableGlobalIdentifierBusiness extends JoinGlobalIdentifierBusiness<IdentifiablePeriodIdentifiableGlobalIdentifier,IdentifiablePeriodIdentifiableGlobalIdentifier.SearchCriteria> {
	
}
