package org.cyk.system.root.persistence.api.mathematics.movement;

import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifier;
import org.cyk.system.root.persistence.api.globalidentification.JoinGlobalIdentifierDao;

public interface MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifierDao extends JoinGlobalIdentifierDao<MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifier,MovementCollectionValuesTransferItemCollectionItemIdentifiableGlobalIdentifier.SearchCriteria> {
	
}
