package org.cyk.system.root.persistence.api.mathematics.movement;

import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollection;
import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollectionItem;

public interface MovementCollectionValuesTransferItemCollectionDao extends AbstractMovementCollectionsDao<MovementCollectionValuesTransferItemCollection,MovementCollectionValuesTransferItemCollectionItem> {

}
