package org.cyk.system.root.persistence.api.mathematics.movement;

import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollection;
import org.cyk.system.root.model.mathematics.movement.MovementCollectionValuesTransferItemCollectionItem;
import org.cyk.system.root.persistence.api.AbstractCollectionDao;

public interface MovementCollectionValuesTransferItemCollectionDao extends AbstractCollectionDao<MovementCollectionValuesTransferItemCollection,MovementCollectionValuesTransferItemCollectionItem> {

}
