package org.cyk.system.root.persistence.impl.mathematics.machine;

import java.io.Serializable;

import org.cyk.system.root.model.mathematics.machine.FiniteStateMachineTransitionIdentifiableGlobalIdentifier;
import org.cyk.system.root.persistence.api.mathematics.machine.FiniteStateMachineTransitionIdentifiableGlobalIdentifierDao;
import org.cyk.system.root.persistence.impl.globalidentification.AbstractJoinGlobalIdentifierDaoImpl;

public class FiniteStateMachineTransitionIdentifiableGlobalIdentifierDaoImpl extends AbstractJoinGlobalIdentifierDaoImpl<FiniteStateMachineTransitionIdentifiableGlobalIdentifier,FiniteStateMachineTransitionIdentifiableGlobalIdentifier.SearchCriteria> implements FiniteStateMachineTransitionIdentifiableGlobalIdentifierDao,Serializable {

	private static final long serialVersionUID = 6306356272165070761L;

}
 