package org.cyk.system.root.persistence.impl.transfer;

import java.io.Serializable;

import org.cyk.system.root.model.transfer.TransferItemCollectionItemIdentifiableGlobalIdentifier;
import org.cyk.system.root.persistence.api.transfer.TransferItemCollectionItemIdentifiableGlobalIdentifierDao;
import org.cyk.system.root.persistence.impl.globalidentification.AbstractJoinGlobalIdentifierDaoImpl;

public class TransferItemCollectionItemIdentifiableGlobalIdentifierDaoImpl extends AbstractJoinGlobalIdentifierDaoImpl<TransferItemCollectionItemIdentifiableGlobalIdentifier,TransferItemCollectionItemIdentifiableGlobalIdentifier.SearchCriteria> implements TransferItemCollectionItemIdentifiableGlobalIdentifierDao,Serializable {
	private static final long serialVersionUID = 6306356272165070761L;
	

}
 